version: '3.8'

services:
  # MySQL Database Service
  mysql-database:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_DATABASE: dcm_db
      MYSQL_ROOT_PASSWORD: Root12345!
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped


  # Spring Boot Application Service
  dcm-app:
    build: .
    container_name: spring-boot-app
    depends_on:
      - mysql-database
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-database:3306/dcm_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root12345!
      SPRING_MAIL_USERNAME: atelierfeliscluj@gmail.com
      SPRING_MAIL_PASSWORD: jfqd dkmg rerk ebgw
    restart: unless-stopped


  keycloak-server:
      image: quay.io/keycloak/keycloak:22.0.1
      container_name: keycloak-server
      ports:
        - "7080:8080"
      environment:
        KEYCLOAK_ADMIN: "admin"
        KEYCLOAK_ADMIN_PASSWORD: "admin"
      command: "start-dev"

volumes:
   mysql-data: